NTA_MAPPING_GRAPH = {
    "Downtown Brooklyn-DUMBO-Boerum Hill" : "Downtown Brooklyn-DUMBO",
    "Highland Park-Cypress Hills Cemeteries (South)" : "Highland Park (South)",
    "Carroll Gardens-Cobble Hill-Gowanus-Red Hook" : "Carroll Gardens",
    "Prospect Lefferts Gardens-Wingate" : "Prospect Lefferts Gardens",
    "Sunset Park (East)-Borough Park (West)" : "Sunset Park (East)",
    "Flatbush (West)-Ditmas Park-Parkville" : "Flatbush (West)",
    "Sheepshead Bay-Manhattan Beach-Gerritsen Beach" : "Sheepshead Bay",
    "Marine Park-Mill Basin-Bergen Beach" : "Marine Park-Mill Basin",
    "Barren Island-Floyd Bennett Field" : "Barren Island",
    "Claremont Village-Claremont (East)" : "Claremont East",
    "Yankee Stadium-Macombs Dam Park" : "Yankee Stadium",
    "University Heights (South)-Morris Heights" : "University Heights (South)",
    "University Heights (North)-Fordham" : "University Heights (North)",
    "Kingsbridge Heights-Van Cortlandt Village" : "Kingsbridge Heights",
    "Pelham Bay-Country Club-City Island" : "Pelham Bay",
    "Ferry Point Park-St. Raymond Cemetery" : "Ferry Point Park",
    "Eastchester-Edenwald-Baychester" : "Eastchester-Edenwald",
    "Financial District-Battery Park City" : "FiDi-Battery Park",
    "The Battery-Governors Island-Ellis Island-Liberty Island" : "Battery-Governors Island",
    "SoHo-Little Italy-Hudson Square" : "SoHo-Little Italy-Hudson Sq",
    "Midtown South-Flatiron-Union Square" : "Flatiron-Union Square",
    "Stuyvesant Town-Peter Cooper Village" : "Stuyvesant Town",
    "Upper West Side-Manhattan Valley" : "Upper West Side",
    "Upper East Side-Lenox Hill-Roosevelt Island" : "Upper East Side",
    "Astoria (North)-Ditmars-Steinway" : "Astoria (North)",
    "Astoria (East)-Woodside (North)" : "Astoria (East)",
    "Queensbridge-Ravenswood-Dutch Kills" : "Queensbridge",
    "Calvary & Mount Zion Cemeteries" : "Calvary - Mt. Zion Cemeteries",
    "Mount Olivet & All Faiths Cemeteries" : "Mt. Olivet Cemetery",
    "Highland Park-Cypress Hills Cemeteries (North)" : "Highland Park (North)",
    "Mount Hebron & Cedar Grove Cemeteries" : "Mt. Hebron Cemetery",
    "Springfield Gardens (North)-Rochdale Village" : "Springfield Gardens (North)",
    "Glen Oaks-Floral Park-New Hyde Park" : "Glen Oaks-Floral Park",
    "Springfield Gardens (South)-Brookville" : "Springfield Gardens (South)",
    "Rockaway Beach-Arverne-Edgemere" : "Rockaway Beach",
    "Breezy Point-Belle Harbor-Rockaway Park-Broad Channel" : "Breezy Point-Belle Harbor",
    "John F. Kennedy International Airport" : "JFK Airport",
    "Jacob Riis Park-Fort Tilden-Breezy Point Tip" : "Jacob Riis Park",
    "Tompkinsville-Stapleton-Clifton-Fox Hills" : "Tompkinsville-Stapleton",
    "West New Brighton-Silver Lake-Grymes Hill" : "West New Brighton",
    "Mariner's Harbor-Arlington-Graniteville" : "Mariner's Harbor-Arlington",
    "Grasmere-Arrochar-South Beach-Dongan Hills" : "Grasmere-Arrochar",
    "Todt Hill-Emerson Hill-Lighthouse Hill-Manor Heights" : "Todt Hill",
    "New Springville-Willowbrook-Bulls Head-Travis" : "New Springville",
    "Annadale-Huguenot-Prince's Bay-Woodrow" : "Annadale-Huguenot",
}


OVERVIEW_DESCRIPTION="""
A pixel-by-pixel reading of land-surface temperature (LST) against vegetation (NDVI) across New York City neighborhoods, from Landsat 8 thermal imagery on clear summer days.
"""